# This file was *autogenerated* from the file pollard.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_110545695839248001 = Integer(110545695839248001); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
n = _sage_const_110545695839248001 
#n = 53098980256925153592047
a0 = _sage_const_1 
b0 = _sage_const_1 
c = _sage_const_1 

import fractions

a0 = (a0**_sage_const_2  + c) % n
b0 = (((b0**_sage_const_2  + c)**_sage_const_2 ) + c) % n
p = fractions.gcd(abs(b0 - a0), n)
if(p > _sage_const_1 ):
	print ("Found a factor: " + str(p))


while (a0 != b0):
	a0 = (a0**_sage_const_2  + c) % n
	b0 = (((b0**_sage_const_2  + c)**_sage_const_2 ) + c) % n
	p = fractions.gcd(abs(b0 - a0), n)
	if(p > _sage_const_1 ):
		print ("Found a factor: " + str(p))
		n = n / p
